/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin_interface;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import static admin_interface.Admin_Myprofile.countlines;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Admin_Officer_Modify extends javax.swing.JFrame {

    /**
     * Creates new form navigator
     */
    public Admin_Officer_Modify() {
        initComponents();
        Officers1.setBackground(Color.white);
        Officers2.setForeground(Color.black);
        LocalDate mydate = LocalDate.now();
        String today = mydate.toString();
        date2.setText(today);
        String[] Session = User.mySession;
        username2.setText(Session[7]);
        // Set Alert Messages into Invisible
        mydata1.setVisible(false);
        mydata2.setVisible(false);
        mydata3.setVisible(false);
        mydata4.setVisible(false);
        mydata5.setVisible(false);
        mydata6.setVisible(false);
        mydata7.setVisible(false);
        mydata8.setVisible(false);
        
        reset.setEnabled(false);
        save.setEnabled(false);
        
        name.setEditable(false);
        email.setEditable(false);
        username.setEditable(false);
        password.setEditable(false);
        phone.setEditable(false);
        ic.setEditable(false);
        gender.setEnabled(false);
        role.setEnabled(false);
        
        String[] officer_data = Officer.officer_info;
        
        name.setText(officer_data[0]);
        email.setText(officer_data[1]);
        phone.setText(officer_data[3]);
        ic.setText(officer_data[4]);
        date.setText(officer_data[5]);
        username.setText(officer_data[7]);
        password.setText(officer_data[8]);
        
        String mygender = officer_data[2];
        String myrole = officer_data[6];
        
        int check_gender = 0;
        int check_role = 0;
        
        if (mygender.equals("Male")){
            check_gender = 1;
        }else if(mygender.equals("Female")){
            check_gender = 2;
        }
        
        if (myrole.equals("Administrator")){
            check_role = 1;
        }else if(myrole.equals("Officer")){
            check_role = 2;
        }else if(myrole.equals("Sales Person")){
            check_role = 3;
        }
        
        gender.setSelectedIndex(check_gender);

        role.setSelectedIndex(check_role);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        navigator = new javax.swing.JPanel();
        Reports1 = new javax.swing.JPanel();
        Reports2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        Dashboard1 = new javax.swing.JPanel();
        Dashboard2 = new javax.swing.JLabel();
        Register1 = new javax.swing.JPanel();
        Register2 = new javax.swing.JLabel();
        Admins1 = new javax.swing.JPanel();
        Admins2 = new javax.swing.JLabel();
        Officers1 = new javax.swing.JPanel();
        Officers2 = new javax.swing.JLabel();
        Sales1 = new javax.swing.JPanel();
        Sales2 = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        role1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        role2 = new javax.swing.JLabel();
        username2 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        LogoutBtn = new javax.swing.JLabel();
        profile = new javax.swing.JButton();
        background1 = new javax.swing.JPanel();
        navigator1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Reports3 = new javax.swing.JPanel();
        Reports4 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        Dashboard3 = new javax.swing.JPanel();
        Dashboard4 = new javax.swing.JLabel();
        Register3 = new javax.swing.JPanel();
        Register4 = new javax.swing.JLabel();
        Admins3 = new javax.swing.JPanel();
        Admins4 = new javax.swing.JLabel();
        Officers3 = new javax.swing.JPanel();
        Officers4 = new javax.swing.JLabel();
        Sales3 = new javax.swing.JPanel();
        Sales4 = new javax.swing.JLabel();
        username3 = new javax.swing.JLabel();
        role3 = new javax.swing.JLabel();
        date3 = new javax.swing.JLabel();
        role4 = new javax.swing.JLabel();
        username4 = new javax.swing.JLabel();
        date4 = new javax.swing.JLabel();
        Logout1 = new javax.swing.JPanel();
        LogoutBtn1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        ic = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        mydata1 = new javax.swing.JLabel();
        mydata3 = new javax.swing.JLabel();
        mydata4 = new javax.swing.JLabel();
        mydata2 = new javax.swing.JLabel();
        mydata7 = new javax.swing.JLabel();
        mydata6 = new javax.swing.JLabel();
        show1 = new javax.swing.JLabel();
        mydata5 = new javax.swing.JLabel();
        mydata8 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        profile1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        regdate = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        save = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        modeSwitch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navigator.setBackground(new java.awt.Color(0, 0, 0));
        navigator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Reports1.setBackground(new java.awt.Color(0, 0, 0));
        Reports1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reports1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Reports1MouseClicked(evt);
            }
        });
        Reports1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Reports2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Reports2.setForeground(new java.awt.Color(255, 255, 255));
        Reports2.setText("Reports");
        Reports1.add(Reports2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 5, 100, 30));
        Reports1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        navigator.add(Reports1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 160, 40));

        Dashboard1.setBackground(new java.awt.Color(0, 0, 0));
        Dashboard1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dashboard1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Dashboard1MouseClicked(evt);
            }
        });
        Dashboard1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dashboard2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Dashboard2.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard2.setText("Dashboard");
        Dashboard2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dashboard1.add(Dashboard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, 20));

        navigator.add(Dashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, 40));

        Register1.setBackground(new java.awt.Color(0, 0, 0));
        Register1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Register1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Register1MouseClicked(evt);
            }
        });
        Register1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Register2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Register2.setForeground(new java.awt.Color(255, 255, 255));
        Register2.setText("Registration");
        Register1.add(Register2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 110, 40));

        navigator.add(Register1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 160, 40));

        Admins1.setBackground(new java.awt.Color(0, 0, 0));
        Admins1.setForeground(new java.awt.Color(255, 255, 255));
        Admins1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Admins1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admins1MouseClicked(evt);
            }
        });
        Admins1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Admins2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Admins2.setForeground(new java.awt.Color(255, 255, 255));
        Admins2.setText("Admins");
        Admins1.add(Admins2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, 20));

        navigator.add(Admins1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 160, 40));

        Officers1.setBackground(new java.awt.Color(0, 0, 0));
        Officers1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Officers1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Officers1MouseClicked(evt);
            }
        });
        Officers1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Officers2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Officers2.setForeground(new java.awt.Color(255, 255, 255));
        Officers2.setText("Officers");
        Officers1.add(Officers2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, 20));

        navigator.add(Officers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 160, 40));

        Sales1.setBackground(new java.awt.Color(0, 0, 0));
        Sales1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sales1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sales1MouseClicked(evt);
            }
        });
        Sales1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sales2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Sales2.setForeground(new java.awt.Color(255, 255, 255));
        Sales2.setText("Sales Person");
        Sales1.add(Sales2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        navigator.add(Sales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 160, 40));

        username1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        username1.setForeground(new java.awt.Color(255, 255, 255));
        username1.setText("Username :");
        navigator.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        role1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        role1.setForeground(new java.awt.Color(255, 255, 255));
        role1.setText("Role :");
        navigator.add(role1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        date1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        date1.setForeground(new java.awt.Color(255, 255, 255));
        date1.setText("Date :");
        navigator.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        role2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        role2.setForeground(new java.awt.Color(255, 255, 255));
        role2.setText("Admin");
        navigator.add(role2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        username2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        username2.setForeground(new java.awt.Color(255, 255, 255));
        username2.setText("Sample");
        navigator.add(username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 90, -1));

        date2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        date2.setForeground(new java.awt.Color(255, 255, 255));
        date2.setText("DD/MM/YYYY");
        navigator.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 120, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Yoyo Furniture");
        navigator.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        background.add(navigator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 490));

        Logout.setBackground(new java.awt.Color(255, 255, 255));
        Logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.jpg"))); // NOI18N
        LogoutBtn.setText("Logout");
        LogoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.add(LogoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        background.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 100, 40));

        profile.setBackground(new java.awt.Color(0, 0, 0));
        profile.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setText("My Profile");
        profile.setBorder(null);
        profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        background.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 100, 40));

        background1.setBackground(new java.awt.Color(255, 255, 255));
        background1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navigator1.setBackground(new java.awt.Color(0, 0, 0));
        navigator1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Yoyo - World");
        navigator1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, -1));

        Reports3.setBackground(new java.awt.Color(0, 0, 0));
        Reports3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reports3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Reports3MouseClicked(evt);
            }
        });
        Reports3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Reports4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Reports4.setForeground(new java.awt.Color(255, 255, 255));
        Reports4.setText("Reports");
        Reports3.add(Reports4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 5, 100, 30));
        Reports3.add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        navigator1.add(Reports3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 160, 40));

        Dashboard3.setBackground(new java.awt.Color(0, 0, 0));
        Dashboard3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dashboard3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Dashboard3MouseClicked(evt);
            }
        });
        Dashboard3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dashboard4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Dashboard4.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard4.setText("Dashboard");
        Dashboard4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dashboard3.add(Dashboard4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, 20));

        navigator1.add(Dashboard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, 40));

        Register3.setBackground(new java.awt.Color(0, 0, 0));
        Register3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Register3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Register3MouseClicked(evt);
            }
        });
        Register3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Register4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Register4.setForeground(new java.awt.Color(255, 255, 255));
        Register4.setText("Registration");
        Register3.add(Register4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 110, 40));

        navigator1.add(Register3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 160, 40));

        Admins3.setBackground(new java.awt.Color(0, 0, 0));
        Admins3.setForeground(new java.awt.Color(255, 255, 255));
        Admins3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Admins3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admins3MouseClicked(evt);
            }
        });
        Admins3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Admins4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Admins4.setForeground(new java.awt.Color(255, 255, 255));
        Admins4.setText("Admins");
        Admins3.add(Admins4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, 20));

        navigator1.add(Admins3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 160, 40));

        Officers3.setBackground(new java.awt.Color(0, 0, 0));
        Officers3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Officers3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Officers3MouseClicked(evt);
            }
        });
        Officers3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Officers4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Officers4.setForeground(new java.awt.Color(255, 255, 255));
        Officers4.setText("Officers");
        Officers3.add(Officers4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, 20));

        navigator1.add(Officers3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 160, 40));

        Sales3.setBackground(new java.awt.Color(0, 0, 0));
        Sales3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sales3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sales3MouseClicked(evt);
            }
        });
        Sales3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sales4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Sales4.setForeground(new java.awt.Color(255, 255, 255));
        Sales4.setText("Sales Person");
        Sales3.add(Sales4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        navigator1.add(Sales3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 160, 40));

        username3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        username3.setForeground(new java.awt.Color(255, 255, 255));
        username3.setText("Username :");
        navigator1.add(username3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        role3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        role3.setForeground(new java.awt.Color(255, 255, 255));
        role3.setText("Role :");
        navigator1.add(role3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        date3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        date3.setForeground(new java.awt.Color(255, 255, 255));
        date3.setText("Date :");
        navigator1.add(date3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        role4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        role4.setForeground(new java.awt.Color(255, 255, 255));
        role4.setText("Admin");
        navigator1.add(role4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        username4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        username4.setForeground(new java.awt.Color(255, 255, 255));
        username4.setText("ABC123");
        navigator1.add(username4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 90, -1));

        date4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        date4.setForeground(new java.awt.Color(255, 255, 255));
        date4.setText("DD/MM/YYYY");
        navigator1.add(date4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 120, -1));

        background1.add(navigator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 490));

        Logout1.setBackground(new java.awt.Color(255, 255, 255));
        Logout1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Logout1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout1MouseClicked(evt);
            }
        });
        Logout1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoutBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogoutBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.jpg"))); // NOI18N
        LogoutBtn1.setText("Logout");
        LogoutBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout1.add(LogoutBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        background1.add(Logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 100, 40));
        background1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 230, -1));

        jLabel5.setText("Name :");
        background1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel6.setText("Gender :");
        background1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Administrator", "Officer", "Sales Person" }));
        background1.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 230, -1));

        jLabel7.setText("Email :");
        background1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jLabel8.setText("Phone Number :");
        background1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, -1));
        background1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 230, -1));

        jLabel9.setText("Role :");
        background1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, -1, -1));
        background1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 230, -1));

        jLabel10.setText("Username :");
        background1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));
        background1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 230, -1));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Male", "Female" }));
        background1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 230, -1));

        jLabel11.setText("IC Number :");
        background1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, -1, -1));
        background1.add(ic, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 230, -1));

        jLabel13.setText("Password :");
        background1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));
        background1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 230, -1));

        mydata1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        mydata1.setForeground(new java.awt.Color(255, 0, 51));
        mydata1.setText("Invalid Name Entered !");
        background1.add(mydata1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        mydata3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        mydata3.setForeground(new java.awt.Color(255, 0, 51));
        mydata3.setText("Invalid Email Format !");
        background1.add(mydata3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        mydata4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        mydata4.setForeground(new java.awt.Color(255, 0, 51));
        mydata4.setText("Invalid Phone Number !");
        background1.add(mydata4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        mydata2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        mydata2.setForeground(new java.awt.Color(255, 0, 51));
        mydata2.setText("Please Select an Option !");
        background1.add(mydata2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        mydata7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        mydata7.setForeground(new java.awt.Color(255, 0, 51));
        mydata7.setText("Invalid IC Number !");
        background1.add(mydata7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, -1, -1));

        mydata6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        mydata6.setForeground(new java.awt.Color(255, 0, 51));
        mydata6.setText("Min-length 6 Must include Upper and Lower Case !");
        background1.add(mydata6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        show1.setText("Show");
        show1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show1MouseClicked(evt);
            }
        });
        background1.add(show1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 50, -1));

        mydata5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        mydata5.setForeground(new java.awt.Color(255, 0, 51));
        mydata5.setText("Please Select an Option !");
        background1.add(mydata5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, -1));

        mydata8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        mydata8.setForeground(new java.awt.Color(255, 51, 51));
        mydata8.setText("Invalid Username !");
        background1.add(mydata8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        reset.setBackground(new java.awt.Color(0, 0, 0));
        reset.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("Reset");
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        background1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 90, 30));

        profile1.setBackground(new java.awt.Color(0, 0, 0));
        profile1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        profile1.setForeground(new java.awt.Color(255, 255, 255));
        profile1.setText("My Profile");
        profile1.setBorder(null);
        profile1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile1ActionPerformed(evt);
            }
        });
        background1.add(profile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 100, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("Officer Profile");
        background1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        date.setEditable(false);
        background1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 120, 30));

        regdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        regdate.setText("Registration Date : ");
        background1.add(regdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 120, 30));

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        background1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, -1, -1));

        save.setBackground(new java.awt.Color(0, 0, 0));
        save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        background1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, -1, -1));

        deleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 0, 0));
        deleteBtn.setText("Delete Account");
        deleteBtn.setBorder(null);
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        background1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 160, 30));

        modeSwitch.setBackground(new java.awt.Color(255, 255, 255));
        modeSwitch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        modeSwitch.setText(" Edit Mode");
        modeSwitch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modeSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeSwitchActionPerformed(evt);
            }
        });
        background1.add(modeSwitch, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 100, 30));

        background.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 530));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        int n = JOptionPane.showConfirmDialog(null,"Would you like to Logout" + " ?", "Logout", JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION){
            String[] Session = User.mySession;
            for (int i = 0; i < Session.length; i++) {
                Session[i] = "";
            }
         
            Login a = new Login();
            a.setVisible(true);
            this.setVisible(false); 
        }
    }//GEN-LAST:event_LogoutMouseClicked

    private void Register1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register1MouseClicked
        try {
            Admin_Registration a = new Admin_Registration();
            a.setVisible(true);
            this.setVisible(false); 
        } catch (IOException ex) {
            Logger.getLogger(Admin_Officer_Modify.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Register1MouseClicked

    private void Dashboard1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dashboard1MouseClicked
        try {
            Admin_Dashboard a = new Admin_Dashboard();
            a.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(Admin_Officer_Modify.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Dashboard1MouseClicked

    private void Admins1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admins1MouseClicked
        Admin_Admin_List a = new Admin_Admin_List();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Admins1MouseClicked

    private void Officers1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Officers1MouseClicked
        Admin_Officer_List a = new Admin_Officer_List();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Officers1MouseClicked

    private void Sales1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sales1MouseClicked
        Admin_Sale_List a = new Admin_Sale_List();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Sales1MouseClicked

    private void Reports1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reports1MouseClicked
        Admin_Reports a = new Admin_Reports();        
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Reports1MouseClicked

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        Admin_Myprofile a = new Admin_Myprofile();        
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_profileActionPerformed

    private void Reports3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reports3MouseClicked
        Admin_Reports a = new Admin_Reports();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Reports3MouseClicked

    private void Dashboard3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dashboard3MouseClicked
        try {
            Admin_Dashboard a = new Admin_Dashboard();
            a.setVisible(true);
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Admin_Registration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Admin_Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Dashboard3MouseClicked

    private void Register3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register3MouseClicked
        try {
            Admin_Registration a = new Admin_Registration();
            a.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(Admin_Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Register3MouseClicked

    private void Admins3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admins3MouseClicked
        Admin_Admin_List a = new Admin_Admin_List();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Admins3MouseClicked

    private void Officers3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Officers3MouseClicked
        Admin_Officer_List a = new Admin_Officer_List();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Officers3MouseClicked

    private void Sales3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sales3MouseClicked
        Admin_Sale_List a = new Admin_Sale_List();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Sales3MouseClicked

    private void Logout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout1MouseClicked
        int n = JOptionPane.showConfirmDialog(null,"Would you like to Logout" + " ?", "Logout", JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION){
            String[] Session = User.mySession;
            for (int i = 0; i < Session.length; i++) {
                Session[i] = "";
            }

            Login a = new Login();
            a.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_Logout1MouseClicked

    private void show1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show1MouseClicked
        // Show / Unshow Password Section
        password.setEchoChar(password.getEchoChar() == 0 ? '\u2022' : (char) 0);
        show1.setText(password.getEchoChar() == 0 ? "Unshow" : "Show");
    }//GEN-LAST:event_show1MouseClicked

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // Resetting information back to default
        int n = JOptionPane.showConfirmDialog(null,"Would you like to reset the Data" + " ?", "Reset", JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION){
            String[] officer_data = Officer.officer_info;
            name.setText(officer_data[0]);
            email.setText(officer_data[1]);
            phone.setText(officer_data[3]);
            ic.setText(officer_data[4]);
            date.setText(officer_data[5]);
            username.setText(officer_data[7]);
            password.setText(officer_data[8]);

            String mygender = officer_data[2];
            String myrole = officer_data[6];
        
            int check_gender = 0;
            int check_role = 0;

            if (mygender.equals("Male")){
                check_gender = 1;
            }else if(mygender.equals("Female")){
                check_gender = 2;
            }

            if (myrole.equals("Administrator")){
                check_role = 1;
            }else if(myrole.equals("Officer")){
                check_role = 2;
            }else if(myrole.equals("Sales Person")){
                check_role = 3;
            }

            gender.setSelectedIndex(check_gender);

            role.setSelectedIndex(check_role);
            }
    }//GEN-LAST:event_resetActionPerformed

    private void profile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile1ActionPerformed
        Admin_Myprofile a = new Admin_Myprofile();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_profile1ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
            Admin_Officer_List a = new Admin_Officer_List();
            a.setVisible(true);
            this.setVisible(false); 
    }//GEN-LAST:event_backBtnActionPerformed
        boolean editMode = true;
    private void modeSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeSwitchActionPerformed

        editMode = !editMode;

        // Update the button text based on the current mode
        if (editMode) {
            modeSwitch.setText("Edit Mode");
            name.setEditable(false);
            email.setEditable(false);
            username.setEditable(false);
            password.setEditable(false);
            phone.setEditable(false);
            ic.setEditable(false);
            gender.setEnabled(false);
            role.setEnabled(false);
            reset.setEnabled(false);
            save.setEnabled(false);
            
        } else {
            modeSwitch.setText("View Mode");
            name.setEditable(true);
            email.setEditable(true);
            username.setEditable(true);
            password.setEditable(true);
            phone.setEditable(true);
            ic.setEditable(true);
            gender.setEnabled(true);
            role.setEnabled(true);
            reset.setEnabled(true);
            save.setEnabled(true);
        }

        
            
    }//GEN-LAST:event_modeSwitchActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // Deleting Officer Data
        String[] officer_data = Officer.officer_info;
        int n = JOptionPane.showConfirmDialog(null,"Delete this officer " + officer_data[0] + " / " + officer_data[7] + " ?", "Reset", JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION){
            try {
                Officer obj1 = new Officer(officer_data[7]);
                String res = obj1.delete_Officer();
                if (res == "Success"){
                  JOptionPane.showMessageDialog(null,"Record Deleted !","Success",JOptionPane.INFORMATION_MESSAGE);
                    Admin_Officer_List a = new Admin_Officer_List();
                    a.setVisible(true);
                    this.setVisible(false); 
                  
                }  
            } catch (IOException ex) {
                Logger.getLogger(Admin_Officer_Modify.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
       // Save the modfified Data
        try {
            String style = ".*[!@#$%^&*()\\-_=+\\[\\]{};:\'\"<>,./?\\\\|`~].*";
            
            
            String fullname, emailadd, genders, phonenum, icnum, roles, myusername, mypassword, mydate;
            Boolean Bname = false;
            Boolean Bemail = false;
            Boolean Bgender = false;
            Boolean Bphone = false;
            Boolean Bic = false;
            Boolean Brole = false;
            Boolean Busername = false;
            Boolean Bpassword = false;
            Boolean checkic = false;
            Boolean checkusername = false;
            Boolean checkemail = false;
            
            fullname = name.getText();
            emailadd = email.getText();
            genders = String.valueOf(gender.getSelectedItem());
            phonenum = phone.getText();
            icnum = ic.getText();
            roles = String.valueOf(role.getSelectedItem());
            myusername = username.getText();
            mypassword = password.getText();
            mydate = date.getText();
            RandomAccessFile raf = new RandomAccessFile("user.txt", "rw");
            
            
            int totalRecords = countlines() / 10;
            
            if (totalRecords == 0) {
                checkusername = true;
                checkic = true;
                checkemail = true;
            }
            else{
                for (int i = 0; i < countlines() / 10; i++) {
                    
                    String data1, data2, data3, data4, data5, data6, data7, data8, data9, data10;
                    
                    data1 = raf.readLine().substring(6);
                    data2 = raf.readLine().substring(7);
                    data3 = raf.readLine().substring(8);
                    data4 = raf.readLine().substring(7);
                    data5 = raf.readLine().substring(4);
                    data6 = raf.readLine().substring(15);
                    data7 = raf.readLine().substring(6);
                    data8 = raf.readLine().substring(10);
                    data9 = raf.readLine().substring(10);
                    data10 = raf.readLine().substring(0);
                    
                    String[] officer_data = Officer.officer_info;
                    // Checking Username Data From user.txt
                    if (data8.equals(officer_data[7])) {
                       checkusername = true;    
                    }
                    else if(data8.equals(myusername)){
                       JOptionPane.showMessageDialog(null, "Username is registered, please use another username!", "Error", JOptionPane.INFORMATION_MESSAGE);
                       username.setText("");
                       checkusername = false;
                       break;
                    }
                    else {
                       checkusername = true;
                    }
                    // Checking Email Data From user.txt
                    if(data2.equals(officer_data[1])){
                        checkemail = true;
                    }
                    else if (data2.equals(emailadd)){
                        JOptionPane.showMessageDialog(null,"Email is registered please use another email!","Error",JOptionPane.INFORMATION_MESSAGE);
                        email.setText("");
                        checkemail = false;
                        break;
                    }
                    else{
                   // Checking IC Data From user.txt
                    if(data5.equals(officer_data[4])){
                        checkic = true; 
                    }
                    else if(data5.equals(icnum)){
                       JOptionPane.showMessageDialog(null,"IC is registered!","Error",JOptionPane.INFORMATION_MESSAGE);
                       ic.setText("");
                       checkic = false;
                       break;
                    }
                    else{
                        checkic = true;
                    }          checkemail = true;
                    }

                    // Checking IC Data From user.txt
                    if(data5.equals(officer_data[4])){
                        checkic = true; 
                    }
                    else if(data5.equals(icnum)){
                       JOptionPane.showMessageDialog(null,"IC is registered!","Error",JOptionPane.INFORMATION_MESSAGE);
                       ic.setText("");
                       checkic = false;
                       break;
                    }
                    else{
                        checkic = true;
                    }
                    
                }
            }       

            //name validation
            
            if (fullname.length() < 3 || fullname.isEmpty()){
                mydata1.setVisible(true);
            } else if (fullname.matches(".*\\d+.*")|| fullname.matches(style)){
                mydata1.setVisible(true);
            } else{
                Bname = true;
                mydata1.setVisible(false);
            }
            //email validation
            if ((emailadd == null || emailadd.isEmpty())){
                mydata3.setVisible(true);
            } else if (!emailadd.contains("@") || (!emailadd.contains(".com"))){
                mydata3.setVisible(true);
            } else{
                Bemail = true;
                mydata3.setVisible(false);
            }   
            
            //gender validation
            
            if(genders == "None"){
                mydata2.setVisible(true);
            }else{
                Bgender = true;
                mydata2.setVisible(false);
            }
            
            //phone number validation

            if(phonenum.length() != 10 && phonenum.length() != 11){
                mydata4.setVisible(true);
            }else if (phonenum.matches(".*[a-zA-Z].*") && phonenum.isEmpty()){
                mydata4.setVisible(true);
            }else{
                mydata4.setVisible(false);
                Bphone = true;
            }  
            
            //ic number validation

            if(icnum.length() != 12){
                mydata7.setVisible(true);
            }else if(icnum.matches(".*[a-zA-Z].*")){
                mydata7.setVisible(true);
            }else{
                Bic = true;
                mydata7.setVisible(false);
            }   


            //roles validation

            if(roles == "None"){
                mydata5.setVisible(true);
            }else{
                Brole = true;
                mydata5.setVisible(false);
            }   

            //username validation
            
            if (myusername.length() < 3 || myusername.isEmpty()){
                mydata8.setVisible(true);
            } else if (myusername.matches(style)){
                mydata8.setVisible(true);
            } else{
                Busername = true;
                mydata8.setVisible(false);
            } 
            
            //password validation
            
            if ( mypassword.isEmpty()) {
                mydata6.setVisible(true);
            }else if (mypassword.length() < 6){
                mydata6.setVisible(true);
            }else if (!mypassword.matches(".*[A-Z].*") || !mypassword.matches(".*[a-z].*")){
                mydata6.setVisible(true);
            }else{
                Bpassword = true;
                mydata6.setVisible(false);
            }   
            
            if (Bname && Bemail && Bgender && Bphone && Bic && Brole && Busername && Bpassword && checkic && checkusername && checkemail){
                
                int n = JOptionPane.showConfirmDialog(null,"Proceed with Modification " + " ?", "Modify Data ?", JOptionPane.YES_NO_OPTION);
                if(n==JOptionPane.YES_OPTION){
                    String[] officer_data = Officer.officer_info;
                    
                    Officer obj1 = new Officer(fullname, emailadd, genders, phonenum, icnum, mydate, roles, myusername, mypassword);
                    String res = obj1.modify_Officer();
                    
                    if(res == "Success"){
                        JOptionPane.showMessageDialog(null,"Modification Sucess !","Success",JOptionPane.INFORMATION_MESSAGE);
 
                        Admin_Officer_List a = new Admin_Officer_List();
                        a.setVisible(true);
                        this.setVisible(false);
                        
                    }else
                        JOptionPane.showMessageDialog(null, "Please try again! Something happened","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Admin_Officer_Modify.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Admin_Officer_Modify.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Officer_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Officer_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Officer_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Officer_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Officer_Modify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Admins1;
    private javax.swing.JLabel Admins2;
    private javax.swing.JPanel Admins3;
    private javax.swing.JLabel Admins4;
    private javax.swing.JPanel Dashboard1;
    private javax.swing.JLabel Dashboard2;
    private javax.swing.JPanel Dashboard3;
    private javax.swing.JLabel Dashboard4;
    private javax.swing.JPanel Logout;
    private javax.swing.JPanel Logout1;
    private javax.swing.JLabel LogoutBtn;
    private javax.swing.JLabel LogoutBtn1;
    private javax.swing.JPanel Officers1;
    private javax.swing.JLabel Officers2;
    private javax.swing.JPanel Officers3;
    private javax.swing.JLabel Officers4;
    private javax.swing.JPanel Register1;
    private javax.swing.JLabel Register2;
    private javax.swing.JPanel Register3;
    private javax.swing.JLabel Register4;
    private javax.swing.JPanel Reports1;
    private javax.swing.JLabel Reports2;
    private javax.swing.JPanel Reports3;
    private javax.swing.JLabel Reports4;
    private javax.swing.JPanel Sales1;
    private javax.swing.JLabel Sales2;
    private javax.swing.JPanel Sales3;
    private javax.swing.JLabel Sales4;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel background;
    private javax.swing.JPanel background1;
    private javax.swing.JTextField date;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel date3;
    private javax.swing.JLabel date4;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField email;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField ic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton modeSwitch;
    private javax.swing.JLabel mydata1;
    private javax.swing.JLabel mydata2;
    private javax.swing.JLabel mydata3;
    private javax.swing.JLabel mydata4;
    private javax.swing.JLabel mydata5;
    private javax.swing.JLabel mydata6;
    private javax.swing.JLabel mydata7;
    private javax.swing.JLabel mydata8;
    private javax.swing.JTextField name;
    private javax.swing.JPanel navigator;
    private javax.swing.JPanel navigator1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JButton profile;
    private javax.swing.JButton profile1;
    private javax.swing.JLabel regdate;
    private javax.swing.JButton reset;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JLabel role1;
    private javax.swing.JLabel role2;
    private javax.swing.JLabel role3;
    private javax.swing.JLabel role4;
    private javax.swing.JButton save;
    private javax.swing.JLabel show1;
    private javax.swing.JTextField username;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username2;
    private javax.swing.JLabel username3;
    private javax.swing.JLabel username4;
    // End of variables declaration//GEN-END:variables
}
