/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin_interface;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.time.LocalDate;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Admin_Myprofile extends javax.swing.JFrame {

    /**
     * Creates new form navigator
     */
    public Admin_Myprofile() {
        initComponents();
        LocalDate mydate = LocalDate.now();
        String today = mydate.toString();
        date2.setText(today);
        String[] Session = User.mySession;
        username2.setText(Session[7]);
        // Set Alert Messages into invisible
        nameoop1.setVisible(false);
        nameoop2.setVisible(false);
        nameoop3.setVisible(false);
        nameoop4.setVisible(false);
        nameoop5.setVisible(false);
        nameoop6.setVisible(false);
        nameoop7.setVisible(false);
        nameoop8.setVisible(false);
        
        String mygender = Session[2];
        String myrole = Session[6];
        int check_gender = 0;
        int check_role = 0;
        // Handle Gender Information to Convert into Correct JComboBox index
        if (mygender.equals("Male")){
            check_gender = 1;
        }else if(mygender.equals("Female")){
            check_gender = 2;
        }
        // Handle Role Information to Convert into Correct JComboBox index
        if (myrole.equals("Administrator")){
            check_role = 1;
        }else if(myrole.equals("Officer")){
            check_role = 2;
        }else if(myrole.equals("Sales Person")){
            check_role = 3;
        }
        // Show Data 
        name.setText(Session[0]);
        gender.setSelectedIndex(check_gender);
        email.setText(Session[1]);
        phone.setText(Session[3]);
        role.setSelectedIndex(check_role);
        username.setText(Session[7]);
        password.setText(Session[8]);
        ic.setText(Session[4]);
        date.setText(Session[5]);
    }
    
    static int countlines() throws FileNotFoundException {
        File file = new File("user.txt");
        Scanner scanner = new Scanner(file);
        int count = 0;

        while (scanner.hasNextLine()) {
            scanner.nextLine();
            count++;
        }

        scanner.close();

        return count; // Returns the total number of lines (records)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        navigator = new javax.swing.JPanel();
        Reports1 = new javax.swing.JPanel();
        Reports2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        Dashboard1 = new javax.swing.JPanel();
        Dashboard2 = new javax.swing.JLabel();
        Register1 = new javax.swing.JPanel();
        Register2 = new javax.swing.JLabel();
        Admins1 = new javax.swing.JPanel();
        Admins2 = new javax.swing.JLabel();
        Officers1 = new javax.swing.JPanel();
        Officers2 = new javax.swing.JLabel();
        Sales1 = new javax.swing.JPanel();
        Sales2 = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        role1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        role2 = new javax.swing.JLabel();
        username2 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        LogoutBtn = new javax.swing.JLabel();
        profile = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        regdate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        role = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        ic = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        showpw = new javax.swing.JLabel();
        nameoop2 = new javax.swing.JLabel();
        nameoop1 = new javax.swing.JLabel();
        nameoop3 = new javax.swing.JLabel();
        nameoop4 = new javax.swing.JLabel();
        nameoop5 = new javax.swing.JLabel();
        nameoop6 = new javax.swing.JLabel();
        nameoop7 = new javax.swing.JLabel();
        nameoop8 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navigator.setBackground(new java.awt.Color(0, 0, 0));
        navigator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Reports1.setBackground(new java.awt.Color(0, 0, 0));
        Reports1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reports1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Reports1MouseClicked(evt);
            }
        });
        Reports1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Reports2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Reports2.setForeground(new java.awt.Color(255, 255, 255));
        Reports2.setText("Reports");
        Reports1.add(Reports2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 5, 100, 30));
        Reports1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        navigator.add(Reports1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 160, 40));

        Dashboard1.setBackground(new java.awt.Color(0, 0, 0));
        Dashboard1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dashboard1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Dashboard1MouseClicked(evt);
            }
        });
        Dashboard1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dashboard2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Dashboard2.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard2.setText("Dashboard");
        Dashboard2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dashboard1.add(Dashboard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, 20));

        navigator.add(Dashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, 40));

        Register1.setBackground(new java.awt.Color(0, 0, 0));
        Register1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Register1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Register1MouseClicked(evt);
            }
        });
        Register1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Register2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Register2.setForeground(new java.awt.Color(255, 255, 255));
        Register2.setText("Registration");
        Register1.add(Register2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 110, 40));

        navigator.add(Register1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 160, 40));

        Admins1.setBackground(new java.awt.Color(0, 0, 0));
        Admins1.setForeground(new java.awt.Color(255, 255, 255));
        Admins1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Admins1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admins1MouseClicked(evt);
            }
        });
        Admins1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Admins2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Admins2.setForeground(new java.awt.Color(255, 255, 255));
        Admins2.setText("Admins");
        Admins1.add(Admins2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, 20));

        navigator.add(Admins1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 160, 40));

        Officers1.setBackground(new java.awt.Color(0, 0, 0));
        Officers1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Officers1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Officers1MouseClicked(evt);
            }
        });
        Officers1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Officers2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Officers2.setForeground(new java.awt.Color(255, 255, 255));
        Officers2.setText("Officers");
        Officers1.add(Officers2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, 20));

        navigator.add(Officers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 160, 40));

        Sales1.setBackground(new java.awt.Color(0, 0, 0));
        Sales1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sales1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sales1MouseClicked(evt);
            }
        });
        Sales1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sales2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Sales2.setForeground(new java.awt.Color(255, 255, 255));
        Sales2.setText("Sales Person");
        Sales1.add(Sales2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        navigator.add(Sales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 160, 40));

        username1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        username1.setForeground(new java.awt.Color(255, 255, 255));
        username1.setText("Username :");
        navigator.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        role1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        role1.setForeground(new java.awt.Color(255, 255, 255));
        role1.setText("Role :");
        navigator.add(role1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        date1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        date1.setForeground(new java.awt.Color(255, 255, 255));
        date1.setText("Date :");
        navigator.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        role2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        role2.setForeground(new java.awt.Color(255, 255, 255));
        role2.setText("Admin");
        navigator.add(role2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        username2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        username2.setForeground(new java.awt.Color(255, 255, 255));
        username2.setText("Sample");
        navigator.add(username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 90, -1));

        date2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        date2.setForeground(new java.awt.Color(255, 255, 255));
        date2.setText("DD/MM/YYYY");
        navigator.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 120, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Yoyo Furniture");
        navigator.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        background.add(navigator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 490));

        Logout.setBackground(new java.awt.Color(255, 255, 255));
        Logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.jpg"))); // NOI18N
        LogoutBtn.setText("Logout");
        LogoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.add(LogoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        background.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 100, 40));

        profile.setBackground(new java.awt.Color(255, 255, 255));
        profile.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        profile.setText("My Profile");
        profile.setBorder(null);
        profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        background.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 100, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("My Profile");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        regdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        regdate.setText("Registration Date : ");
        background.add(regdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 110, 30));

        jLabel3.setText("Name :");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));
        background.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 220, -1));

        jLabel4.setText("Gender :");
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, -1, -1));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Male", "Female" }));
        background.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 220, -1));

        jLabel5.setText("Email :");
        background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        jLabel6.setText("Phone Number :");
        background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));
        background.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 220, -1));
        background.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 220, -1));

        jLabel7.setText("Username :");
        background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        jLabel8.setText("Role :");
        background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, -1));
        background.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 220, -1));

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Administrator", "Officer", "Sales Person" }));
        background.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 220, -1));

        jLabel9.setText("Password :");
        background.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        jLabel10.setText("IC Number :");
        background.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, -1, -1));
        background.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 220, -1));
        background.add(ic, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 220, -1));

        reset.setBackground(new java.awt.Color(0, 0, 0));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("Reset");
        reset.setBorder(null);
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        background.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 80, 30));

        edit.setBackground(new java.awt.Color(0, 0, 0));
        edit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("Edit");
        edit.setBorder(null);
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        background.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 70, 30));

        showpw.setText("Show");
        showpw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showpwMouseClicked(evt);
            }
        });
        background.add(showpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 50, -1));

        nameoop2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        nameoop2.setForeground(new java.awt.Color(255, 51, 51));
        nameoop2.setText("Please Select an Option !");
        background.add(nameoop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        nameoop1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        nameoop1.setForeground(new java.awt.Color(255, 51, 51));
        nameoop1.setText("Name Invalid !");
        background.add(nameoop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        nameoop3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        nameoop3.setForeground(new java.awt.Color(255, 51, 51));
        nameoop3.setText("Email Invalid !");
        background.add(nameoop3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        nameoop4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        nameoop4.setForeground(new java.awt.Color(255, 51, 51));
        nameoop4.setText("Phone Number Invalid !");
        background.add(nameoop4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, -1));

        nameoop5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        nameoop5.setForeground(new java.awt.Color(255, 51, 51));
        nameoop5.setText("Username Invalid !");
        background.add(nameoop5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        nameoop6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        nameoop6.setForeground(new java.awt.Color(255, 51, 51));
        nameoop6.setText("Please Select an Option !");
        background.add(nameoop6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, -1));

        nameoop7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        nameoop7.setForeground(new java.awt.Color(255, 51, 51));
        nameoop7.setText("Password Invalid !");
        background.add(nameoop7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, -1, -1));

        nameoop8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        nameoop8.setForeground(new java.awt.Color(255, 51, 51));
        nameoop8.setText("IC Number Invalid !");
        background.add(nameoop8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, -1));

        date.setEditable(false);
        background.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 110, 30));

        deleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 0, 51));
        deleteBtn.setText("Terminate Account");
        deleteBtn.setBorder(null);
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        background.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 150, 30));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        int n = JOptionPane.showConfirmDialog(null,"Would you like to Logout" + " ?", "Logout", JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION){
            String[] Session = User.mySession;
            for (int i = 0; i < Session.length; i++) {
                Session[i] = "";
            }
            
            Login a = new Login();
            a.setVisible(true);
            this.setVisible(false); 
        }
    }//GEN-LAST:event_LogoutMouseClicked

    private void Register1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register1MouseClicked
        try {
            Admin_Registration a = new Admin_Registration();
            a.setVisible(true);
            this.setVisible(false); 
        } catch (IOException ex) {
            Logger.getLogger(Admin_Myprofile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Register1MouseClicked

    private void Dashboard1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dashboard1MouseClicked
        try {
            Admin_Dashboard a = new Admin_Dashboard();
            a.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(Admin_Myprofile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Dashboard1MouseClicked

    private void Admins1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admins1MouseClicked
        Admin_Admin_List a = new Admin_Admin_List();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Admins1MouseClicked

    private void Officers1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Officers1MouseClicked
        Admin_Officer_List a = new Admin_Officer_List();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Officers1MouseClicked

    private void Sales1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sales1MouseClicked
        Admin_Sale_List a = new Admin_Sale_List();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Sales1MouseClicked

    private void Reports1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reports1MouseClicked
        Admin_Reports a = new Admin_Reports();        
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Reports1MouseClicked

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        Admin_Myprofile a = new Admin_Myprofile();        
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_profileActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        int n = JOptionPane.showConfirmDialog(null,"Would you like to reset the Data" + " ?", "Reset", JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION){
            // Function to Reset Data Back to Default
            String[] Session = User.mySession;
            String mygender = Session[2];
            String myrole = Session[6];
            int check_gender = 0;
            int check_role = 0;

            if (mygender.equals("Male")){
                check_gender = 1;
            }else if(mygender.equals("Female")){
                check_gender = 2;
            }

            if (myrole.equals("Administrator")){
                check_role = 1;
            }else if(myrole.equals("Officer")){
                check_role = 2;
            }else if(myrole.equals("Sales Person")){
                check_role = 3;
            }
            // Display Data    
            name.setText(Session[0]);
            gender.setSelectedIndex(check_gender);
            email.setText(Session[1]);
            phone.setText(Session[3]);
            role.setSelectedIndex(check_role);
            username.setText(Session[7]);
            password.setText(Session[8]);
            ic.setText(Session[4]);
            date.setText(Session[5]);
        }
          
        
    }//GEN-LAST:event_resetActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
    try{    
        String style = ".*[!@#$%^&*()\\-_=+\\[\\]{};:\'\"<>,./?\\\\|`~].*";
        
        String[] Session = User.mySession;
        
        String fullname, emailadd, genders, phonenum, icnum, roles, myusername, mypassword, mydate;

        Boolean Bname = false;
        Boolean Bemail = false;
        Boolean Bgender = false;
        Boolean Bphone = false;
        Boolean Bic = false;
        Boolean Brole = false;
        Boolean Busername = false;
        Boolean Bpassword = false;
        Boolean checkic = false;
        Boolean checkusername = false;
        Boolean checkemail = false;
        
        fullname = name.getText();
        emailadd = email.getText();
        genders = String.valueOf(gender.getSelectedItem());
        phonenum = phone.getText();
        icnum = ic.getText();
        roles = String.valueOf(role.getSelectedItem());
        myusername = username.getText();
        mypassword = password.getText();
        mydate = date.getText();
        
        
            
        RandomAccessFile raf = new RandomAccessFile("user.txt", "rw");
        
        int totalRecords = countlines() / 10;
        
        if (totalRecords == 0) {
            checkusername = true;
            checkic = true;
            checkemail = true;
        } 
        else{
        for (int i = 0; i < countlines() / 10; i++) {
            
            String data1, data2, data3, data4, data5, data6, data7, data8, data9, data10; 
            
            data1 = raf.readLine().substring(6);
            data2 = raf.readLine().substring(7);
            data3 = raf.readLine().substring(8);
            data4 = raf.readLine().substring(7);
            data5 = raf.readLine().substring(4);
            data6 = raf.readLine().substring(15);
            data7 = raf.readLine().substring(6);
            data8 = raf.readLine().substring(10);
            data9 = raf.readLine().substring(10);
            data10 = raf.readLine().substring(0);
            
            
            
            if (data8.equals(Session[7])) {
                checkusername = true;    
            }
            else if(data8.equals(myusername)){
                JOptionPane.showMessageDialog(null, "Username is registered, please use another username!", "Error", JOptionPane.INFORMATION_MESSAGE);
                username.setText("");
                checkusername = false;
                break;
            }
            else {
                checkusername = true;
            }

            
            if(data2.equals(Session[1])){
                checkemail = true;
            }
            else if (data2.equals(emailadd)){
                JOptionPane.showMessageDialog(null,"Email is registered please use another email!","Error",JOptionPane.INFORMATION_MESSAGE);
                email.setText("");
                checkemail = false;
                break;
            }
            else{
               checkemail = true;
            }
 
             if(data5.equals(Session[4])){
                 checkic = true; 
             }
             else if(data5.equals(icnum)){
                JOptionPane.showMessageDialog(null,"IC is registered!","Error",JOptionPane.INFORMATION_MESSAGE);
                ic.setText("");
                checkic = false;
                break;
             }
             else{
                 checkic = true;
             }
        }
    }
 
        //name validation
        if (fullname.length() < 3 || fullname.isEmpty()){
            nameoop1.setVisible(true);
        } else if (fullname.matches(".*\\d+.*")|| fullname.matches(style)){
            nameoop1.setVisible(true);
        } else{
            Bname = true;
            nameoop1.setVisible(false);
        }
        
        //email validation
        if ((emailadd == null || emailadd.isEmpty())){
            nameoop3.setVisible(true);
        } else if (!emailadd.contains("@") || (!emailadd.contains(".com"))){
            nameoop3.setVisible(true);
        } else{
            Bemail = true;
            nameoop3.setVisible(false);
        }
        
        //gender validation
        if(genders == "None"){
            nameoop2.setVisible(true);
        }else{
            Bgender = true;
            nameoop2.setVisible(false);
        }
        
        //phone number validation
        if(phonenum.length() != 10 && phonenum.length() != 11){
            nameoop4.setVisible(true);
        }else if (phonenum.matches(".*[a-zA-Z].*") && phonenum.isEmpty()){
            nameoop4.setVisible(true);
        }else{
            nameoop4.setVisible(false);
            Bphone = true;
        }
        
        //ic number validation
        if(icnum.length() != 12){
            nameoop8.setVisible(true);
        }else if(icnum.matches(".*[a-zA-Z].*")){
            nameoop8.setVisible(true);
        }else{
            Bic = true;
            nameoop8.setVisible(false);
        }
        
        //roles validation
        if(roles == "None"){
            nameoop6.setVisible(true);
        }else{
            Brole = true;
            nameoop6.setVisible(false);
        }
        
        
        //username validation
        if (myusername.length() < 3 || myusername.isEmpty()){
            nameoop5.setVisible(true);
        } else if (myusername.matches(style)){
            nameoop5.setVisible(true);
        } else{
            Busername = true;
            nameoop5.setVisible(false);
        }
        
        //password validation
        if ( mypassword.isEmpty()) {
            nameoop7.setVisible(true);
        }else if (mypassword.length() < 6){
            nameoop7.setVisible(true);
        }else if (!mypassword.matches(".*[A-Z].*") || !mypassword.matches(".*[a-z].*")){
            nameoop7.setVisible(true);
        }else{
            Bpassword = true;
            nameoop7.setVisible(false);
        }
        
        
        if (Bname && Bemail && Bgender && Bphone && Bic && Brole && Busername && Bpassword && checkic && checkusername && checkemail){
                       
            int n = JOptionPane.showConfirmDialog(null,"Proceed with Modification " + " ?", "Modify Data ?", JOptionPane.YES_NO_OPTION);
            if(n==JOptionPane.YES_OPTION){
                
                Admin admin = new Admin(fullname, emailadd, genders, phonenum, icnum, mydate, roles, myusername, mypassword);

                String res = admin.modify_admin_profile();

                if(res == "Success"){
                    JOptionPane.showMessageDialog(null,"Modification Sucess, Please Login Again.","Success",JOptionPane.INFORMATION_MESSAGE);
                    for (int i = 0; i < Session.length; i++) {
                        Session[i] = "";
                    }
                    Login a = new Login();
                    a.setVisible(true);
                    this.setVisible(false); 

                }else
                    JOptionPane.showMessageDialog(null, "Please try again! Something happened","Error",JOptionPane.ERROR_MESSAGE);
                }  
            }
        
    }   catch (IOException ex) {
            Logger.getLogger(Admin_Registration.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }//GEN-LAST:event_editActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
            int n = JOptionPane.showConfirmDialog(null,"Are you sure you want to Delete Your Account" + " ?", "Delete?", JOptionPane.YES_NO_OPTION);
            if(n==JOptionPane.YES_OPTION){
                
                int m = JOptionPane.showConfirmDialog(null,"Second confirmation to Delete Account" + " ?", "Delete?", JOptionPane.YES_NO_OPTION);
                if(m==JOptionPane.YES_OPTION){
                    
                    try {
                        String[] Session = User.mySession;
                        
                        Admin obj1 = new Admin(Session[0], Session[1], Session[2], Session[3], Session[4], Session[5], Session[6], Session[7], Session[8]);
                        String res = obj1.delete_admin_Account();
                        
                        if(res == "Success"){
                            JOptionPane.showMessageDialog(null,"Account Terminated, Heading to Login Page...","Success",JOptionPane.INFORMATION_MESSAGE);
                            for (int i = 0; i < Session.length; i++) {
                                Session[i] = "";
                            }
                            Login a = new Login();
                            a.setVisible(true);
                            this.setVisible(false); 
                        
                        }
                        
                    } catch (IOException ex) {
                        Logger.getLogger(Admin_Myprofile.class.getName()).log(Level.SEVERE, null, ex);
                    }
                
                
                }
            }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void showpwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showpwMouseClicked
        password.setEchoChar(password.getEchoChar() == 0 ? '\u2022' : (char) 0);
        showpw.setText(password.getEchoChar() == 0 ? "Unshow" : "Show");
    }//GEN-LAST:event_showpwMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Myprofile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Admins1;
    private javax.swing.JLabel Admins2;
    private javax.swing.JPanel Dashboard1;
    private javax.swing.JLabel Dashboard2;
    private javax.swing.JPanel Logout;
    private javax.swing.JLabel LogoutBtn;
    private javax.swing.JPanel Officers1;
    private javax.swing.JLabel Officers2;
    private javax.swing.JPanel Register1;
    private javax.swing.JLabel Register2;
    private javax.swing.JPanel Reports1;
    private javax.swing.JLabel Reports2;
    private javax.swing.JPanel Sales1;
    private javax.swing.JLabel Sales2;
    private javax.swing.JPanel background;
    private javax.swing.JTextField date;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton edit;
    private javax.swing.JTextField email;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField ic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameoop1;
    private javax.swing.JLabel nameoop2;
    private javax.swing.JLabel nameoop3;
    private javax.swing.JLabel nameoop4;
    private javax.swing.JLabel nameoop5;
    private javax.swing.JLabel nameoop6;
    private javax.swing.JLabel nameoop7;
    private javax.swing.JLabel nameoop8;
    private javax.swing.JPanel navigator;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JButton profile;
    private javax.swing.JLabel regdate;
    private javax.swing.JButton reset;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JLabel role1;
    private javax.swing.JLabel role2;
    private javax.swing.JLabel showpw;
    private javax.swing.JTextField username;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username2;
    // End of variables declaration//GEN-END:variables
}
